### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by TyhypkoIryna** [TyhypkoIryna/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by TyhypkoIrynaSecond** [comment]
<h2>Résumé<h2/>
His name's not Yoda, and he's only kind of a baby, but The Mandalorian character who's been dubbed Baby Yoda, and is officially called "The Child," is the breakout star of the newish Disney Plus streaming service. Pretty good for a character whose name and species we might never know.

**Comment by TyhypkoIryna** [comment]
Thank you!
