### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by TyhypkoIryna** [TyhypkoIryna/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by TyhypkoIrynaSecond** [comment]
Born and lieved in approximately 41 BBY, during the era of the Galactic Republic.
https://disney.fandom.com/wiki/Grogu
https://starwars.fandom.com/wiki/Grogu
https://uk.wikipedia.org/wiki/%D2%90%D1%80%D0%BE%D2%91%D1%83
