### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by TyhypkoIryna** [TyhypkoIryna/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by TyhypkoIrynaSecond** [comment]
So what do we know about the little critter popularly called Baby Yoda? Let's assemble a FAQ.

**What is he exactly?** 
> He's` of the same species as Yoda, the Jedi Grand Master first introduced in the 1980 film The Empire Strikes Back. Problem is, Yoda's species never got a name or a backstory. They're just smallish green aliens who are extremely Force-sensitive. Star Wars creator George Lucas has always kept Yoda and his ilk somewhat mysterious, which adds to fan interest. 

**Where is he from?**
> Someday we might find out, but not yet. In The Empire Strikes Back, Luke Skywalker meets Yoda on the swampy planet of Dagobah, but he's in exile there, it's not believed to be his home world. The Mandalorian found The Child, aka Baby Yoda, on a desert planet called Arvala-7 that looked a lot like Luke's childhood home of Tatooine. There's no sign that there are more little Yodas around, so that's probably not its species' home world, either.

**Are there more of them?**
> A female creature of this species, Yaddle, was part of the Jedi Council in Star Wars: The Phantom Menace. And another male, Minch, appeared in the comics. And we have no idea if The Child is related to Yoda, or Yaddle, or even Minch, but maybe eventually we'll find out. So far, this is a small species -- maybe they're all on ancestry site 23 and Me.

**Is he even a he?**
> Not sure how they verified this, but The Child is male, at least according to Dr. Pershing (Omid Abtahi), who refers to the baby repeatedly as "him."

**Is he really a baby?**
> He's 50, an infant in this species, which enjoys extraordinarily long lifespans, at least by human standards. Yoda trained Jedi for 800 years, finally peacefully dying at age 900 in 1983's Return of the Jedi. He still shows up as a Force ghost, however, to advise and help characters in need. And apparently he was born naturally, however this species reproduces. We know this because in episode seven, Kuiil declares that Baby Yoda is "too ugly" to have been genetically engineered. Hey, ugly is as ugly says.

**What's his name?**
> We're going to find out eventually. Disney CEO Bob Iger said in an interview on The Star Wars Show that it's not Yoda, nor is it George (after Star Wars creator George Lucas, we assume). Iger says he knows the name, but is sworn to secrecy. He hinted that it will be revealed fairly soon. We're still going to call it Baby Yoda though -- it's pretty much canon now.

**What are his powers?**
> So far, The Child has displayed super-excellent Force sensitivity, which allows him to levitate items and probably do many other things that will come in handy when Mando is backed up against a wall. (He's still young though -- levitating a mudhorn creature tired him out and put him to sleep.) He can do the Force-choke maneuver that Darth Vader showed off in the original Star Wars movie. In episode seven, Mando has to call him off when Baby Yoda goes after Cara Dune, apparently thinking she's trying to hurt Mando in an arm-wrestling match. Baby Yoda also revealed he has healing powers and can close up a wound by simply touching it and concentrating. Like the levitation, though, doing this wears him out.
Yoda was also quite a lightsaber champ, so the little guy will probably excel at that someday. But Yoda had centuries to practice. There's also something valuable inside The Child that evildoers want and think they can extract (yikes) -- maybe the infamous Midi-chlorians that allow for Force detection?

**So he's in danger then?**
> Heck yeah, he's in danger. Title character The Mandalorian (Pedro Pascal), a bounty hunter, was sent out to find him and turn him over for that creepy extraction, but Mando has turned into more of a daddy figure and is now protecting The Child. Let's hope that the little guy's own powers are improving day by day, so he can help save his own cute green skin.

**Comment by TyhypkoIryna** [comment]
Thank you!
