### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by TyhypkoIryna** [TyhypkoIryna/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by TyhypkoIrynaSecond** [comment]
**What else?**

- He eats soup, and maybe frogs. 
- He's excellent at hide-and-seek. 
- He's as inquisitive as any baby, playing with a metal shift knob from Mando's ship even when told not to. 
- The character is mostly a puppet, but sometimes some CGI is used. His voice comes from "a combination of baby samples, bat-eared foxes, kinkajous, & the sound design vocal talents of Dave Acord," according to Lucasfilm sound designer Matthew Wood.
- He trends higher on social media than the Democratic presidential candidates. 
- He's a huge hit in Utah, but less popular in Mississippi.
- The merchandise promoting him was kinda crappy at first (showrunner Jon Favreau said they couldn't get started on products too early for fear or revealing the character), but products are slowly getting better. (One unofficial version on Etsy sells for $300-$500 and has a 14-month waiting list.)
